apiVersion: v1
data:
  Corefile: |
    efs.us-east-1.amazonaws.com {
        hosts {
            10.1.128.117 fs-0b55b92556f847edc.efs.us-east-1.amazonaws.com
            fallthrough
        }
        whoami
    }
    .:53 {
        errors
        health {
            lameduck 5s
          }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system