apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: "3000"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60
  name: worker
  namespace: astra
spec:
  selector:
    app: worker
  type: ClusterIP
  ports:
  - name: worker
    protocol: TCP
    port: 3000
    targetPort: 3000
