apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipe-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 471208936033.dkr.ecr.us-east-1.amazonaws.com
    chart: microservice
    targetRevision: 0.1.0                                  
    helm:
      valuesObject: 
      # FROM HERE
        replicaCount: 2

        # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
        image:
          repository: 471208936033.dkr.ecr.us-east-1.amazonaws.com/recipe-api
          # This sets the pull policy for images.
          pullPolicy: IfNotPresent
          # Overrides the image tag whose default is the chart appVersion.
          tag: "v2"

        # This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
        imagePullSecrets: []
        # This is to override the chart name.
        nameOverride: ""
        fullnameOverride: ""

        # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
        serviceAccount:
          # Specifies whether a service account should be created.
          create: false
          # Automatically mount a ServiceAccount's API credentials?
          automount: true
          # Annotations to add to the service account.
          annotations: {}
          # The name of the service account to use.
          # If not set and create is true, a name is generated using the fullname template.
          name: "reicpe-api"


        service:
          annotations:
            alb.ingress.kubernetes.io/healthcheck-path: /healthz
            alb.ingress.kubernetes.io/healthcheck-port: "8080"
            alb.ingress.kubernetes.io/success-codes: "200"
            alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60
          type: ClusterIP
          port: 8080


        resources: 
          limits:
            cpu: 1
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi

        # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http

        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 10
          targetCPUUtilizationPercentage: 80
          targetMemoryUtilizationPercentage: 80



  destination:
    name: in-cluster        
    namespace: mealmint
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]